name: Build
on:
    # Manual nightly & release
    workflow_dispatch:

run-name: xfce4-terminal
jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4

            - name: prepare
              id: prepare
              run: |
                  echo "strDate=$(TZ=UTC-8 date +%Y-%m-%d)" >> $GITHUB_OUTPUT

            - name: install dependency
              run: |
                  sudo apt-get update
                  sudo apt-get install meson libgtk-3-dev libvte-2.91-dev libxfce4ui-2-dev xsltproc gettext

            - name: make
              run: |
                  meson setup build
                  meson compile -C build

            - name: make
              run: |
                  ls -al build
